### ISSUE TITLE
evaluate.py 의 Recall 계산법

### ISSUE THREAD

**Issue by wlgns0105** [penny4860/object-detector#42]
안녕하세요. 항공대학교 재학중인 대학생인데요

종합설계 주제로 yolo 모델을 사용중이라 mAP 측정 코드를 참고하고 있습니다.

https://github.com/penny4860/object-detector/blob/master/object_detector/evaluate.py

제가 알기론 recall = True Positive / True Positive + False Negative 로

recall = (True Positive / 총 ground-truth Bounding box ) 인데

코드 상에서는

recall = n_relevant / n_gts 로 분모에 False Negative 가 포함되지 않은 것 같는데 맞나요?

**Comment by penny4860** [comment]
@wlgns0105 

일단 ```recall = True Positive / (True Positive + False Negative) = (True Positive / 총 ground-truth Bounding box )``` 수식은 알고계신 내용이 맞습니다.

code 상에서는 

* ```n_relevant```가 True Positive를 의미하고
* ```n_gts```가 말씀하신 총 ground-truth Bounding box의 숫자를 의미합니다.

따라서 code 구현이 말씀하신 수식대로 구현이 된 것이 맞습니다.

**Comment by wlgns0105** [comment]
@penny4860 

답변 감사합니다 질문이 좀 더 있는데

_calc_iou 함수를 보면

detector 의 출력인 boxes 는 여러 개인데 truth_box 는 1개인 것 같습니다.

image 당 1개의 ground-truth bounding box 가 있는 dataset 을 사용하는 건가요?


또한 n_gts = len(dataset[dataset[:, 1] == 1]) 으로

is_positive = ious > 0.5 가 1인 bounding box 개수를 count 한 것 같은데 맞나요?

맞다면 detector 성능이  떨어져서 ious 값이 전부 0.5보다 작다면 gound-truth bounding box 가 있어도

n_gts 에는 count 되지 않을 것 같습니다.


제가 파이썬 코드 이해도가 낮아 질문이 생기는 것 같네요..

**Comment by penny4860** [comment]
* 본 프로젝트에서 사용한 dataset은 object가 image당 1개 또는 0개 였기때문에 single object만 있다는 가정하에 구현했었습니다. multiple object에 대한 precision/recall code 는 [SVHN-deep-digit-detector](https://github.com/penny4860/SVHN-deep-digit-detector/blob/master/digit_detector/evaluate.py) 에서 구현해 두었으니 필요하시면 참고하시기 바랍니다.
* n_gts는 ```is_positive ```와는 무관하게 predefine 되어있는 label 만 가지고 count 합니다. detector 성능과는 무관합니다.

**Comment by wlgns0105** [comment]
넵 답변 감사합니다
